var drinks = document.getElementById("mylist")
var newdrink = document.createElement("li")
//var textnode = document.createTextNode("Water")
newdrink.appendChild (document.createTextNode("Water"))
//newdrink.appendChild(textnode)
drinks.appendChild(newdrink)